name: Deploy Database

on:
  workflow_dispatch:

jobs:

  deploy-db:

    name: Deploy Postrgres RDS

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform on Runner
        uses: hashicorp/setup-terraform@v4
        with:
            terraform_version: "1.15.6"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var="db_username=${{ secrets.POSTGRES_USER }}" -var="db_password=${{ secrets.POSTGRES_PASSWORD }}"

      - name: Get Database Outputs
        run: |
          DB_HOST=$(terraform output -raw db_host)
          DB_PORT=$(terraform output -raw db_port)
          DB_NAME=$(terraform output -raw db_name)

          echo "DB_HOST=$DB_HOST" >> "$GITHUB_ENV"
          echo "DB_PORT=$DB_PORT" >> "$GITHUB_ENV"
          echo "DB_NAME=$DB_NAME" >> "$GITHUB_ENV"

          echo "Database host: $DB_HOST"
          echo "Database port: $DB_PORT"
          echo "Database name: $DB_NAME"


      - name: Trigger Infra after DB deployed
        env:
          GH_TOKEN: ${{ secrets.PAT_REPO_INFRA_LAMBDA }}
          INFRA_REPO: k8s-infra-oficina-mecanica
          ORG_NAME: Grupo-SOAT
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/repos/${ORG_NAME}/${INFRA_REPO}/dispatches" \
            -d "{
              \"event_type\": \"db-deployed\",
              \"client_payload\": {
                \"db_host\": \"${DB_HOST}\",
                \"db_port\": \"${DB_PORT}\",
                \"db_name\": \"${DB_NAME}\"
              }
            }"